services:
  # MongoDB Service
  db:
    image: mongo:4.2
    container_name: db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db

  # Backend (Node/Express)
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: innodev/mern-backend:1.0
    container_name: backend
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      MONGO_URI: mongodb://root:example@db:27017/test?authSource=admin
    networks:
      - mern-network

  # Frontend (React + Nginx)
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: innodev/mern-frontend:1.0
    container_name: frontend
    restart: always
    ports:
      - "80:80"  # Nginx will serve the React app on port 80
    networks:
      - mern-network

# Optional: Define a custom network for communication between services
networks:
  mern-network:
    driver: bridge
