version: '3.8'

services:
  
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: 192.168.33.10:8083/docker-repo/mern-backend:1.0
    container_name: backend
    restart: always
    ports:
      - "5000:5000"
    
    environment:
      MONGO_URI: mongodb://root:example@db:27017/test?authSource=admin
    networks:
      - mern-network
    command: sh -c "sleep infinity"


  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: 192.168.33.10:8083/docker-repo/mern-frontend:1.0
    container_name: frontend
    restart: always
    ports:
      - "80:80"
    networks:
      - mern-network

networks:
  mern-network:
    driver: bridge
