name: Merge Contributor Branches

on:
  workflow_dispatch:  # This allows you to run it manually

jobs:
  merge-branches:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensures full history for merging

      - name: Configure Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

      - name: Merge Contributor Branches into merging-test
        run: |
          git checkout -b merging-test origin/main  # Create test branch from main
          git pull origin main  # Ensure it's up to date

          # List of contributor branches to merge
          branches=("Halim" "ouday" "mahmoud" "Sayf" "eya")

          for branch in "${branches[@]}"; do
            echo "Merging $branch..."
            git merge origin/$branch --no-ff -m "Merging $branch into merging-test"
          done

          git push origin merging-test  # Push the merged test branch
